ALTER TABLE "reading_cards"
ADD COLUMN "is_face_up" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "rotation_deg" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "freeform_x_px" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "freeform_y_px" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "freeform_stack_order" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "grid_column" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "grid_row" INTEGER NOT NULL DEFAULT 0;
